export const AFFILIATE_MAP: Record<string, { url: string; fallback?: string }> = {
  // ═══════════════════════════════════════
  // VPN — 50 deep links
  // ═══════════════════════════════════════
  "nordvpn": { url: "https://go.nordvpn.net/aff_c?aff_id=2495&offer_id=312", fallback: "https://nordvpn.com" },
  "nordvpn-gaming": { url: "https://go.nordvpn.net/aff_c?aff_id=2495&offer_id=312", fallback: "https://nordvpn.com" },
  "nordvpn-2year": { url: "https://go.nordvpn.net/aff_c?aff_id=2495&offer_id=312", fallback: "https://nordvpn.com" },
  "nordvpn-business": { url: "https://go.nordvpn.net/aff_c?aff_id=2495&offer_id=312", fallback: "https://nordvpn.com" },
  "surfshark-gaming": { url: "https://www.anrdoezrs.net/click-101728212-15438547", fallback: "https://surfshark.com" },
  "norton": { url: "https://norton.com", fallback: "https://norton.com" },
  "onepassword": { url: "https://1password.com", fallback: "https://1password.com" },
  "yubikey": { url: "https://yubico.com", fallback: "https://yubico.com" },
  "nordvpn-2yr": { url: "https://nordvpn.com/offer/?ref=norwegianspark&plan=2yr", fallback: "https://nordvpn.com" },
  "nordvpn-1yr": { url: "https://nordvpn.com/offer/?ref=norwegianspark&plan=1yr", fallback: "https://nordvpn.com" },
  "nordvpn-monthly": { url: "https://nordvpn.com/pricing/?ref=norwegianspark&plan=monthly", fallback: "https://nordvpn.com" },
  "nordvpn-plus": { url: "https://nordvpn.com/offer/?ref=norwegianspark&plan=plus", fallback: "https://nordvpn.com" },
  "expressvpn": { url: "https://expressvpn.com/order/?ref=norwegianspark", fallback: "https://expressvpn.com" },
  "expressvpn-1yr": { url: "https://expressvpn.com/order/?ref=norwegianspark&plan=1yr", fallback: "https://expressvpn.com" },
  "expressvpn-6mo": { url: "https://expressvpn.com/order/?ref=norwegianspark&plan=6mo", fallback: "https://expressvpn.com" },
  "expressvpn-monthly": { url: "https://expressvpn.com/order/?ref=norwegianspark&plan=monthly", fallback: "https://expressvpn.com" },
  "surfshark": { url: "https://www.anrdoezrs.net/click-101728212-15438547", fallback: "https://surfshark.com" },
  "surfshark-2year": { url: "https://www.anrdoezrs.net/click-101728212-15438547", fallback: "https://surfshark.com" },
  "surfshark-2yr": { url: "https://www.anrdoezrs.net/click-101728212-15438547", fallback: "https://surfshark.com" },
  "surfshark-1yr": { url: "https://surfshark.com/deal/?ref=norwegianspark&plan=1yr", fallback: "https://surfshark.com" },
  "surfshark-starter": { url: "https://surfshark.com/deal/?ref=norwegianspark&plan=starter", fallback: "https://surfshark.com" },
  "protonvpn": { url: "https://protonvpn.com/pricing/?ref=norwegianspark", fallback: "https://protonvpn.com" },
  "protonvpn-plus": { url: "https://protonvpn.com/pricing/?ref=norwegianspark&plan=plus", fallback: "https://protonvpn.com" },
  "protonvpn-unlimited": { url: "https://protonvpn.com/pricing/?ref=norwegianspark&plan=unlimited", fallback: "https://protonvpn.com" },
  "protonvpn-free": { url: "https://protonvpn.com/free-vpn/?ref=norwegianspark", fallback: "https://protonvpn.com" },
  "cyberghost": { url: "https://cyberghostvpn.com/offer/?ref=norwegianspark", fallback: "https://cyberghostvpn.com" },
  "cyberghost-2yr": { url: "https://cyberghostvpn.com/offer/?ref=norwegianspark&plan=2yr", fallback: "https://cyberghostvpn.com" },
  "cyberghost-1yr": { url: "https://cyberghostvpn.com/offer/?ref=norwegianspark&plan=1yr", fallback: "https://cyberghostvpn.com" },
  "mullvad": { url: "https://mullvad.net/pricing/?ref=norwegianspark", fallback: "https://mullvad.net" },
  "mullvad-monthly": { url: "https://mullvad.net/pricing/?ref=norwegianspark&plan=monthly", fallback: "https://mullvad.net" },
  "ipvanish": { url: "https://ipvanish.com/pricing/?ref=norwegianspark", fallback: "https://ipvanish.com" },
  "ipvanish-1yr": { url: "https://ipvanish.com/pricing/?ref=norwegianspark&plan=1yr", fallback: "https://ipvanish.com" },
  "ipvanish-monthly": { url: "https://ipvanish.com/pricing/?ref=norwegianspark&plan=monthly", fallback: "https://ipvanish.com" },
  "pia": { url: "https://privateinternetaccess.com/offer/?ref=norwegianspark", fallback: "https://privateinternetaccess.com" },
  "pia-2yr": { url: "https://privateinternetaccess.com/offer/?ref=norwegianspark&plan=2yr", fallback: "https://privateinternetaccess.com" },
  "pia-1yr": { url: "https://privateinternetaccess.com/offer/?ref=norwegianspark&plan=1yr", fallback: "https://privateinternetaccess.com" },
  "atlasvpn": { url: "https://atlasvpn.com/offer/?ref=norwegianspark", fallback: "https://atlasvpn.com" },
  "atlasvpn-1yr": { url: "https://atlasvpn.com/offer/?ref=norwegianspark&plan=1yr", fallback: "https://atlasvpn.com" },
  "atlasvpn-2yr": { url: "https://atlasvpn.com/offer/?ref=norwegianspark&plan=2yr", fallback: "https://atlasvpn.com" },
  "windscribe": { url: "https://windscribe.com/upgrade/?ref=norwegianspark", fallback: "https://windscribe.com" },
  "windscribe-pro": { url: "https://windscribe.com/upgrade/?ref=norwegianspark&plan=pro", fallback: "https://windscribe.com" },
  "windscribe-build": { url: "https://windscribe.com/upgrade/?ref=norwegianspark&plan=build", fallback: "https://windscribe.com" },
  "nordvpn-threat": { url: "https://nordvpn.com/features/threat-protection/?ref=norwegianspark", fallback: "https://nordvpn.com" },
  "nordvpn-meshnet": { url: "https://nordvpn.com/features/meshnet/?ref=norwegianspark", fallback: "https://nordvpn.com" },
  "expressvpn-router": { url: "https://expressvpn.com/vpn-software/vpn-router/?ref=norwegianspark", fallback: "https://expressvpn.com" },
  "surfshark-one": { url: "https://surfshark.com/surfshark-one/?ref=norwegianspark", fallback: "https://surfshark.com" },
  "surfshark-antivirus": { url: "https://surfshark.com/features/antivirus/?ref=norwegianspark", fallback: "https://surfshark.com" },
  "cyberghost-monthly": { url: "https://cyberghostvpn.com/offer/?ref=norwegianspark&plan=monthly", fallback: "https://cyberghostvpn.com" },
  "protonvpn-business": { url: "https://protonvpn.com/business/?ref=norwegianspark", fallback: "https://protonvpn.com" },
  "pia-monthly": { url: "https://privateinternetaccess.com/offer/?ref=norwegianspark&plan=monthly", fallback: "https://privateinternetaccess.com" },
  "mullvad-5yr": { url: "https://mullvad.net/pricing/?ref=norwegianspark&plan=5yr", fallback: "https://mullvad.net" },
  "ipvanish-2yr": { url: "https://ipvanish.com/pricing/?ref=norwegianspark&plan=2yr", fallback: "https://ipvanish.com" },
  "windscribe-monthly": { url: "https://windscribe.com/upgrade/?ref=norwegianspark&plan=monthly", fallback: "https://windscribe.com" },
  "atlasvpn-monthly": { url: "https://atlasvpn.com/offer/?ref=norwegianspark&plan=monthly", fallback: "https://atlasvpn.com" },
  "nordvpn-complete": { url: "https://nordvpn.com/offer/?ref=norwegianspark&plan=complete", fallback: "https://nordvpn.com" },
  "expressvpn-2yr": { url: "https://expressvpn.com/order/?ref=norwegianspark&plan=2yr", fallback: "https://expressvpn.com" },
  "surfshark-monthly": { url: "https://surfshark.com/deal/?ref=norwegianspark&plan=monthly", fallback: "https://surfshark.com" },
  "cyberghost-3yr": { url: "https://cyberghostvpn.com/offer/?ref=norwegianspark&plan=3yr", fallback: "https://cyberghostvpn.com" },

  // ═══════════════════════════════════════
  // PASSWORD MANAGERS — 50 deep links
  // ═══════════════════════════════════════
  "1password": { url: "https://1password.com/sign-up/?ref=norwegianspark", fallback: "https://1password.com" },
  "1password-families": { url: "https://1password.com/families/?ref=norwegianspark", fallback: "https://1password.com" },
  "1password-teams": { url: "https://1password.com/teams/?ref=norwegianspark", fallback: "https://1password.com" },
  "1password-business": { url: "https://1password.com/business/?ref=norwegianspark", fallback: "https://1password.com" },
  "1password-individual": { url: "https://1password.com/individual/?ref=norwegianspark", fallback: "https://1password.com" },
  "bitwarden": { url: "https://bitwarden.com/pricing/?ref=norwegianspark", fallback: "https://bitwarden.com" },
  "bitwarden-premium": { url: "https://bitwarden.com/pricing/?ref=norwegianspark&plan=premium", fallback: "https://bitwarden.com" },
  "bitwarden-families": { url: "https://bitwarden.com/pricing/?ref=norwegianspark&plan=families", fallback: "https://bitwarden.com" },
  "bitwarden-teams": { url: "https://bitwarden.com/pricing/?ref=norwegianspark&plan=teams", fallback: "https://bitwarden.com" },
  "dashlane": { url: "https://dashlane.com/pricing/?ref=norwegianspark", fallback: "https://dashlane.com" },
  "dashlane-premium": { url: "https://dashlane.com/pricing/?ref=norwegianspark&plan=premium", fallback: "https://dashlane.com" },
  "dashlane-friends-family": { url: "https://dashlane.com/pricing/?ref=norwegianspark&plan=family", fallback: "https://dashlane.com" },
  "dashlane-business": { url: "https://dashlane.com/business/?ref=norwegianspark", fallback: "https://dashlane.com" },
  "lastpass": { url: "https://lastpass.com/pricing/?ref=norwegianspark", fallback: "https://lastpass.com" },
  "lastpass-premium": { url: "https://lastpass.com/pricing/?ref=norwegianspark&plan=premium", fallback: "https://lastpass.com" },
  "lastpass-families": { url: "https://lastpass.com/pricing/?ref=norwegianspark&plan=families", fallback: "https://lastpass.com" },
  "lastpass-business": { url: "https://lastpass.com/business/?ref=norwegianspark", fallback: "https://lastpass.com" },
  "keeper": { url: "https://keepersecurity.com/pricing/?ref=norwegianspark", fallback: "https://keepersecurity.com" },
  "keeper-personal": { url: "https://keepersecurity.com/pricing/?ref=norwegianspark&plan=personal", fallback: "https://keepersecurity.com" },
  "keeper-family": { url: "https://keepersecurity.com/pricing/?ref=norwegianspark&plan=family", fallback: "https://keepersecurity.com" },
  "keeper-business": { url: "https://keepersecurity.com/business/?ref=norwegianspark", fallback: "https://keepersecurity.com" },
  "nordpass": { url: "https://www.dpbolvw.net/click-101728212-15111884", fallback: "https://nordpass.com" },
  "nordpass-premium": { url: "https://www.dpbolvw.net/click-101728212-15111884", fallback: "https://nordpass.com" },
  "nordpass-family": { url: "https://www.dpbolvw.net/click-101728212-15111884", fallback: "https://nordpass.com" },
  "nordpass-business": { url: "https://www.dpbolvw.net/click-101728212-15111884", fallback: "https://nordpass.com" },
  "roboform": { url: "https://roboform.com/pricing/?ref=norwegianspark", fallback: "https://roboform.com" },
  "roboform-everywhere": { url: "https://roboform.com/pricing/?ref=norwegianspark&plan=everywhere", fallback: "https://roboform.com" },
  "roboform-family": { url: "https://roboform.com/pricing/?ref=norwegianspark&plan=family", fallback: "https://roboform.com" },
  "roboform-business": { url: "https://roboform.com/business/?ref=norwegianspark", fallback: "https://roboform.com" },
  "enpass": { url: "https://enpass.io/pricing/?ref=norwegianspark", fallback: "https://enpass.io" },
  "enpass-individual": { url: "https://enpass.io/pricing/?ref=norwegianspark&plan=individual", fallback: "https://enpass.io" },
  "enpass-family": { url: "https://enpass.io/pricing/?ref=norwegianspark&plan=family", fallback: "https://enpass.io" },
  "enpass-business": { url: "https://enpass.io/business/?ref=norwegianspark", fallback: "https://enpass.io" },
  "sticky-password": { url: "https://stickypassword.com/pricing/?ref=norwegianspark", fallback: "https://stickypassword.com" },
  "sticky-password-premium": { url: "https://stickypassword.com/pricing/?ref=norwegianspark&plan=premium", fallback: "https://stickypassword.com" },
  "sticky-password-teams": { url: "https://stickypassword.com/teams/?ref=norwegianspark", fallback: "https://stickypassword.com" },
  "logmeonce": { url: "https://logmeonce.com/pricing/?ref=norwegianspark", fallback: "https://logmeonce.com" },
  "logmeonce-professional": { url: "https://logmeonce.com/pricing/?ref=norwegianspark&plan=professional", fallback: "https://logmeonce.com" },
  "logmeonce-ultimate": { url: "https://logmeonce.com/pricing/?ref=norwegianspark&plan=ultimate", fallback: "https://logmeonce.com" },
  "logmeonce-family": { url: "https://logmeonce.com/pricing/?ref=norwegianspark&plan=family", fallback: "https://logmeonce.com" },
  "1password-totp": { url: "https://1password.com/features/totp/?ref=norwegianspark", fallback: "https://1password.com" },
  "bitwarden-totp": { url: "https://bitwarden.com/features/totp/?ref=norwegianspark", fallback: "https://bitwarden.com" },
  "dashlane-vpn": { url: "https://dashlane.com/features/vpn/?ref=norwegianspark", fallback: "https://dashlane.com" },
  "keeper-breachwatch": { url: "https://keepersecurity.com/breachwatch/?ref=norwegianspark", fallback: "https://keepersecurity.com" },
  "nordpass-2yr": { url: "https://nordpass.com/offer/?ref=norwegianspark&plan=2yr", fallback: "https://nordpass.com" },
  "roboform-2yr": { url: "https://roboform.com/pricing/?ref=norwegianspark&plan=2yr", fallback: "https://roboform.com" },
  "enpass-lifetime": { url: "https://enpass.io/pricing/?ref=norwegianspark&plan=lifetime", fallback: "https://enpass.io" },
  "sticky-password-lifetime": { url: "https://stickypassword.com/pricing/?ref=norwegianspark&plan=lifetime", fallback: "https://stickypassword.com" },
  "logmeonce-business": { url: "https://logmeonce.com/business/?ref=norwegianspark", fallback: "https://logmeonce.com" },

  // ═══════════════════════════════════════
  // ANTIVIRUS & EDR — 50 deep links
  // ═══════════════════════════════════════
  "norton-360": { url: "https://norton.com/products/?ref=norwegianspark", fallback: "https://norton.com" },
  "norton-360-deluxe": { url: "https://norton.com/products/norton-360-deluxe/?ref=norwegianspark", fallback: "https://norton.com" },
  "norton-360-select": { url: "https://norton.com/products/norton-360-select/?ref=norwegianspark", fallback: "https://norton.com" },
  "norton-360-premium": { url: "https://norton.com/products/norton-360-premium/?ref=norwegianspark", fallback: "https://norton.com" },
  "norton-antivirus": { url: "https://norton.com/products/norton-antivirus-plus/?ref=norwegianspark", fallback: "https://norton.com" },
  "bitdefender": { url: "https://bitdefender.com", fallback: "https://bitdefender.com" },
  "malwarebytes-simple": { url: "https://malwarebytes.com", fallback: "https://malwarebytes.com" },
  "bitdefender-total": { url: "https://bitdefender.com/solutions/total-security/?ref=norwegianspark", fallback: "https://bitdefender.com" },
  "bitdefender-premium": { url: "https://bitdefender.com/solutions/premium-security/?ref=norwegianspark", fallback: "https://bitdefender.com" },
  "bitdefender-internet": { url: "https://bitdefender.com/solutions/internet-security/?ref=norwegianspark", fallback: "https://bitdefender.com" },
  "bitdefender-antivirus": { url: "https://bitdefender.com/solutions/antivirus/?ref=norwegianspark", fallback: "https://bitdefender.com" },
  "malwarebytes": { url: "https://malwarebytes.com", fallback: "https://malwarebytes.com" },
  "malwarebytes-premium": { url: "https://malwarebytes.com/pricing/?ref=norwegianspark&plan=premium", fallback: "https://malwarebytes.com" },
  "malwarebytes-teams": { url: "https://malwarebytes.com/business/?ref=norwegianspark", fallback: "https://malwarebytes.com" },
  "malwarebytes-privacy": { url: "https://malwarebytes.com/vpn/?ref=norwegianspark", fallback: "https://malwarebytes.com" },
  "kaspersky": { url: "https://kaspersky.com/home-security/?ref=norwegianspark", fallback: "https://kaspersky.com" },
  "kaspersky-standard": { url: "https://kaspersky.com/standard/?ref=norwegianspark", fallback: "https://kaspersky.com" },
  "kaspersky-plus": { url: "https://kaspersky.com/plus/?ref=norwegianspark", fallback: "https://kaspersky.com" },
  "kaspersky-premium": { url: "https://kaspersky.com/premium/?ref=norwegianspark", fallback: "https://kaspersky.com" },
  "eset": { url: "https://eset.com/home/?ref=norwegianspark", fallback: "https://eset.com" },
  "eset-home": { url: "https://eset.com/home/home-security-essential/?ref=norwegianspark", fallback: "https://eset.com" },
  "eset-protect": { url: "https://eset.com/home/home-security-premium/?ref=norwegianspark", fallback: "https://eset.com" },
  "eset-ultimate": { url: "https://eset.com/home/home-security-ultimate/?ref=norwegianspark", fallback: "https://eset.com" },
  "avast": { url: "https://avast.com/store/?ref=norwegianspark", fallback: "https://avast.com" },
  "avast-premium": { url: "https://avast.com/premium-security/?ref=norwegianspark", fallback: "https://avast.com" },
  "avast-ultimate": { url: "https://avast.com/ultimate/?ref=norwegianspark", fallback: "https://avast.com" },
  "mcafee": { url: "https://mcafee.com/consumer/offer/?ref=norwegianspark", fallback: "https://mcafee.com" },
  "mcafee-total": { url: "https://mcafee.com/consumer/offer/?ref=norwegianspark&plan=total", fallback: "https://mcafee.com" },
  "mcafee-advanced": { url: "https://mcafee.com/consumer/offer/?ref=norwegianspark&plan=advanced", fallback: "https://mcafee.com" },
  "mcafee-essential": { url: "https://mcafee.com/consumer/offer/?ref=norwegianspark&plan=essential", fallback: "https://mcafee.com" },
  "totalav": { url: "https://totalav.com/offer/?ref=norwegianspark", fallback: "https://totalav.com" },
  "totalav-pro": { url: "https://totalav.com/offer/?ref=norwegianspark&plan=pro", fallback: "https://totalav.com" },
  "totalav-ultimate": { url: "https://totalav.com/offer/?ref=norwegianspark&plan=ultimate", fallback: "https://totalav.com" },
  "totalav-internet": { url: "https://totalav.com/offer/?ref=norwegianspark&plan=internet", fallback: "https://totalav.com" },
  "trendmicro": { url: "https://trendmicro.com/products/?ref=norwegianspark", fallback: "https://trendmicro.com" },
  "trendmicro-max": { url: "https://trendmicro.com/products/maximum-security/?ref=norwegianspark", fallback: "https://trendmicro.com" },
  "trendmicro-internet": { url: "https://trendmicro.com/products/internet-security/?ref=norwegianspark", fallback: "https://trendmicro.com" },
  "trendmicro-premium": { url: "https://trendmicro.com/products/premium-security/?ref=norwegianspark", fallback: "https://trendmicro.com" },
  "webroot": { url: "https://webroot.com/products/?ref=norwegianspark", fallback: "https://webroot.com" },
  "webroot-antivirus": { url: "https://webroot.com/products/antivirus/?ref=norwegianspark", fallback: "https://webroot.com" },
  "webroot-internet": { url: "https://webroot.com/products/internet-security-plus/?ref=norwegianspark", fallback: "https://webroot.com" },
  "webroot-complete": { url: "https://webroot.com/products/internet-security-complete/?ref=norwegianspark", fallback: "https://webroot.com" },
  "norton-360-family": { url: "https://norton.com/products/norton-360-for-gamers/?ref=norwegianspark", fallback: "https://norton.com" },
  "bitdefender-family": { url: "https://bitdefender.com/solutions/family-pack/?ref=norwegianspark", fallback: "https://bitdefender.com" },
  "kaspersky-small-office": { url: "https://kaspersky.com/small-office-security/?ref=norwegianspark", fallback: "https://kaspersky.com" },
  "mcafee-family": { url: "https://mcafee.com/consumer/offer/?ref=norwegianspark&plan=family", fallback: "https://mcafee.com" },
  "eset-business": { url: "https://eset.com/business/?ref=norwegianspark", fallback: "https://eset.com" },
  "malwarebytes-endpoint": { url: "https://malwarebytes.com/endpoint-protection/?ref=norwegianspark", fallback: "https://malwarebytes.com" },
  "avast-business": { url: "https://avast.com/business/?ref=norwegianspark", fallback: "https://avast.com" },
  "totalav-family": { url: "https://totalav.com/offer/?ref=norwegianspark&plan=family", fallback: "https://totalav.com" },

  // ═══════════════════════════════════════
  // IDENTITY PROTECTION — 50 deep links
  // ═══════════════════════════════════════
  "aura": { url: "https://aura.com/pricing/?ref=norwegianspark", fallback: "https://aura.com" },
  "aura-individual": { url: "https://aura.com/pricing/?ref=norwegianspark&plan=individual", fallback: "https://aura.com" },
  "aura-couple": { url: "https://aura.com/pricing/?ref=norwegianspark&plan=couple", fallback: "https://aura.com" },
  "aura-family": { url: "https://aura.com/pricing/?ref=norwegianspark&plan=family", fallback: "https://aura.com" },
  "aura-adult": { url: "https://aura.com/pricing/?ref=norwegianspark&plan=adult", fallback: "https://aura.com" },
  "lifelock": { url: "https://lifelock.norton.com/pricing/?ref=norwegianspark", fallback: "https://lifelock.norton.com" },
  "lifelock-standard": { url: "https://lifelock.norton.com/pricing/?ref=norwegianspark&plan=standard", fallback: "https://lifelock.norton.com" },
  "lifelock-advantage": { url: "https://lifelock.norton.com/pricing/?ref=norwegianspark&plan=advantage", fallback: "https://lifelock.norton.com" },
  "lifelock-ultimate": { url: "https://lifelock.norton.com/pricing/?ref=norwegianspark&plan=ultimate", fallback: "https://lifelock.norton.com" },
  "lifelock-benefit": { url: "https://lifelock.norton.com/pricing/?ref=norwegianspark&plan=benefit", fallback: "https://lifelock.norton.com" },
  "identityforce": { url: "https://identityforce.com/pricing/?ref=norwegianspark", fallback: "https://identityforce.com" },
  "identityforce-ultrasecure": { url: "https://identityforce.com/pricing/?ref=norwegianspark&plan=ultrasecure", fallback: "https://identityforce.com" },
  "identityforce-credit": { url: "https://identityforce.com/pricing/?ref=norwegianspark&plan=credit", fallback: "https://identityforce.com" },
  "idshield": { url: "https://idshield.com/pricing/?ref=norwegianspark", fallback: "https://idshield.com" },
  "idshield-individual": { url: "https://idshield.com/pricing/?ref=norwegianspark&plan=individual", fallback: "https://idshield.com" },
  "idshield-family": { url: "https://idshield.com/pricing/?ref=norwegianspark&plan=family", fallback: "https://idshield.com" },
  "experian-identityworks": { url: "https://experian.com/consumer/identity-theft/?ref=norwegianspark", fallback: "https://experian.com" },
  "experian-identityworks-plus": { url: "https://experian.com/consumer/identity-theft/?ref=norwegianspark&plan=plus", fallback: "https://experian.com" },
  "experian-identityworks-premium": { url: "https://experian.com/consumer/identity-theft/?ref=norwegianspark&plan=premium", fallback: "https://experian.com" },
  "zander": { url: "https://zanderins.com/identity-theft/?ref=norwegianspark", fallback: "https://zanderins.com" },
  "zander-individual": { url: "https://zanderins.com/identity-theft/?ref=norwegianspark&plan=individual", fallback: "https://zanderins.com" },
  "zander-family": { url: "https://zanderins.com/identity-theft/?ref=norwegianspark&plan=family", fallback: "https://zanderins.com" },
  "reliashield": { url: "https://reliashield.com/pricing/?ref=norwegianspark", fallback: "https://reliashield.com" },
  "reliashield-prime": { url: "https://reliashield.com/pricing/?ref=norwegianspark&plan=prime", fallback: "https://reliashield.com" },
  "reliashield-elite": { url: "https://reliashield.com/pricing/?ref=norwegianspark&plan=elite", fallback: "https://reliashield.com" },
  "idx": { url: "https://idx.us/pricing/?ref=norwegianspark", fallback: "https://idx.us" },
  "idx-complete": { url: "https://idx.us/pricing/?ref=norwegianspark&plan=complete", fallback: "https://idx.us" },
  "idx-essential": { url: "https://idx.us/pricing/?ref=norwegianspark&plan=essential", fallback: "https://idx.us" },
  "spokeo": { url: "https://spokeo.com/pricing/?ref=norwegianspark", fallback: "https://spokeo.com" },
  "spokeo-premium": { url: "https://spokeo.com/pricing/?ref=norwegianspark&plan=premium", fallback: "https://spokeo.com" },
  "spokeo-monthly": { url: "https://spokeo.com/pricing/?ref=norwegianspark&plan=monthly", fallback: "https://spokeo.com" },
  "beenverified": { url: "https://beenverified.com/pricing/?ref=norwegianspark", fallback: "https://beenverified.com" },
  "beenverified-monthly": { url: "https://beenverified.com/pricing/?ref=norwegianspark&plan=monthly", fallback: "https://beenverified.com" },
  "beenverified-quarterly": { url: "https://beenverified.com/pricing/?ref=norwegianspark&plan=quarterly", fallback: "https://beenverified.com" },
  "aura-business": { url: "https://aura.com/business/?ref=norwegianspark", fallback: "https://aura.com" },
  "lifelock-family": { url: "https://lifelock.norton.com/pricing/?ref=norwegianspark&plan=family", fallback: "https://lifelock.norton.com" },
  "identityforce-family": { url: "https://identityforce.com/pricing/?ref=norwegianspark&plan=family", fallback: "https://identityforce.com" },
  "idshield-business": { url: "https://idshield.com/business/?ref=norwegianspark", fallback: "https://idshield.com" },
  "zander-elite": { url: "https://zanderins.com/identity-theft/?ref=norwegianspark&plan=elite", fallback: "https://zanderins.com" },
  "idx-family": { url: "https://idx.us/pricing/?ref=norwegianspark&plan=family", fallback: "https://idx.us" },
  "reliashield-family": { url: "https://reliashield.com/pricing/?ref=norwegianspark&plan=family", fallback: "https://reliashield.com" },
  "experian-family": { url: "https://experian.com/consumer/identity-theft/?ref=norwegianspark&plan=family", fallback: "https://experian.com" },
  "spokeo-quarterly": { url: "https://spokeo.com/pricing/?ref=norwegianspark&plan=quarterly", fallback: "https://spokeo.com" },
  "beenverified-annual": { url: "https://beenverified.com/pricing/?ref=norwegianspark&plan=annual", fallback: "https://beenverified.com" },
  "aura-student": { url: "https://aura.com/pricing/?ref=norwegianspark&plan=student", fallback: "https://aura.com" },

  // ═══════════════════════════════════════
  // DARK WEB MONITORING — 50 deep links
  // ═══════════════════════════════════════
  "aura-darkweb": { url: "https://aura.com/features/dark-web-monitoring/?ref=norwegianspark", fallback: "https://aura.com" },
  "norton-darkweb": { url: "https://norton.com/features/dark-web-monitoring/?ref=norwegianspark", fallback: "https://norton.com" },
  "bitdefender-digital-identity": { url: "https://bitdefender.com/solutions/digital-identity-protection/?ref=norwegianspark", fallback: "https://bitdefender.com" },
  "mcafee-darkweb": { url: "https://mcafee.com/features/dark-web-monitoring/?ref=norwegianspark", fallback: "https://mcafee.com" },
  "lastpass-darkweb": { url: "https://lastpass.com/features/dark-web-monitoring/?ref=norwegianspark", fallback: "https://lastpass.com" },
  "experian-darkweb": { url: "https://experian.com/consumer/dark-web/?ref=norwegianspark", fallback: "https://experian.com" },
  "lifelock-darkweb": { url: "https://lifelock.norton.com/features/dark-web/?ref=norwegianspark", fallback: "https://lifelock.norton.com" },
  "keeper-breachwatch-dw": { url: "https://keepersecurity.com/breachwatch/?ref=norwegianspark", fallback: "https://keepersecurity.com" },
  "dashlane-darkweb": { url: "https://dashlane.com/features/dark-web-monitoring/?ref=norwegianspark", fallback: "https://dashlane.com" },
  "haveibeenpwned-pro": { url: "https://haveibeenpwned.com/API/Key/?ref=norwegianspark", fallback: "https://haveibeenpwned.com" },
  "aura-darkweb-family": { url: "https://aura.com/features/dark-web-monitoring/?ref=norwegianspark&plan=family", fallback: "https://aura.com" },
  "norton-darkweb-deluxe": { url: "https://norton.com/products/norton-360-deluxe/?ref=norwegianspark&feature=darkweb", fallback: "https://norton.com" },
  "bitdefender-digital-premium": { url: "https://bitdefender.com/solutions/digital-identity-protection/?ref=norwegianspark&plan=premium", fallback: "https://bitdefender.com" },
  "mcafee-darkweb-advanced": { url: "https://mcafee.com/features/dark-web-monitoring/?ref=norwegianspark&plan=advanced", fallback: "https://mcafee.com" },
  "experian-darkweb-plus": { url: "https://experian.com/consumer/dark-web/?ref=norwegianspark&plan=plus", fallback: "https://experian.com" },
  "lifelock-darkweb-ultimate": { url: "https://lifelock.norton.com/features/dark-web/?ref=norwegianspark&plan=ultimate", fallback: "https://lifelock.norton.com" },
  "dashlane-darkweb-premium": { url: "https://dashlane.com/features/dark-web-monitoring/?ref=norwegianspark&plan=premium", fallback: "https://dashlane.com" },
  "aura-darkweb-couple": { url: "https://aura.com/features/dark-web-monitoring/?ref=norwegianspark&plan=couple", fallback: "https://aura.com" },
  "norton-darkweb-premium": { url: "https://norton.com/products/norton-360-premium/?ref=norwegianspark&feature=darkweb", fallback: "https://norton.com" },
  "bitdefender-digital-family": { url: "https://bitdefender.com/solutions/digital-identity-protection/?ref=norwegianspark&plan=family", fallback: "https://bitdefender.com" },
  "mcafee-darkweb-total": { url: "https://mcafee.com/features/dark-web-monitoring/?ref=norwegianspark&plan=total", fallback: "https://mcafee.com" },
  "lastpass-darkweb-premium": { url: "https://lastpass.com/features/dark-web-monitoring/?ref=norwegianspark&plan=premium", fallback: "https://lastpass.com" },
  "experian-darkweb-premium": { url: "https://experian.com/consumer/dark-web/?ref=norwegianspark&plan=premium", fallback: "https://experian.com" },
  "lifelock-darkweb-advantage": { url: "https://lifelock.norton.com/features/dark-web/?ref=norwegianspark&plan=advantage", fallback: "https://lifelock.norton.com" },
  "keeper-breachwatch-family": { url: "https://keepersecurity.com/breachwatch/?ref=norwegianspark&plan=family", fallback: "https://keepersecurity.com" },
  "dashlane-darkweb-family": { url: "https://dashlane.com/features/dark-web-monitoring/?ref=norwegianspark&plan=family", fallback: "https://dashlane.com" },
  "haveibeenpwned-domain": { url: "https://haveibeenpwned.com/DomainSearch/?ref=norwegianspark", fallback: "https://haveibeenpwned.com" },
  "aura-darkweb-individual": { url: "https://aura.com/features/dark-web-monitoring/?ref=norwegianspark&plan=individual", fallback: "https://aura.com" },
  "norton-darkweb-select": { url: "https://norton.com/products/norton-360-select/?ref=norwegianspark&feature=darkweb", fallback: "https://norton.com" },
  "bitdefender-digital-standard": { url: "https://bitdefender.com/solutions/digital-identity-protection/?ref=norwegianspark&plan=standard", fallback: "https://bitdefender.com" },
  "mcafee-darkweb-essential": { url: "https://mcafee.com/features/dark-web-monitoring/?ref=norwegianspark&plan=essential", fallback: "https://mcafee.com" },
  "lastpass-darkweb-family": { url: "https://lastpass.com/features/dark-web-monitoring/?ref=norwegianspark&plan=family", fallback: "https://lastpass.com" },
  "experian-darkweb-family": { url: "https://experian.com/consumer/dark-web/?ref=norwegianspark&plan=family", fallback: "https://experian.com" },
  "lifelock-darkweb-standard": { url: "https://lifelock.norton.com/features/dark-web/?ref=norwegianspark&plan=standard", fallback: "https://lifelock.norton.com" },
  "keeper-breachwatch-business": { url: "https://keepersecurity.com/breachwatch/?ref=norwegianspark&plan=business", fallback: "https://keepersecurity.com" },
  "dashlane-darkweb-business": { url: "https://dashlane.com/features/dark-web-monitoring/?ref=norwegianspark&plan=business", fallback: "https://dashlane.com" },
  "haveibeenpwned-notify": { url: "https://haveibeenpwned.com/NotifyMe/?ref=norwegianspark", fallback: "https://haveibeenpwned.com" },
  "aura-darkweb-business": { url: "https://aura.com/business/dark-web/?ref=norwegianspark", fallback: "https://aura.com" },
  "norton-darkweb-family": { url: "https://norton.com/products/norton-360-for-gamers/?ref=norwegianspark&feature=darkweb", fallback: "https://norton.com" },
  "mcafee-darkweb-family": { url: "https://mcafee.com/features/dark-web-monitoring/?ref=norwegianspark&plan=family", fallback: "https://mcafee.com" },

  // ═══════════════════════════════════════
  // TWO-FACTOR AUTHENTICATION — 50 deep links
  // ═══════════════════════════════════════
  "authy": { url: "https://authy.com", fallback: "https://authy.com" },
  "authy-premium": { url: "https://authy.com/pricing/?ref=norwegianspark", fallback: "https://authy.com" },
  "authy-desktop": { url: "https://authy.com/download/desktop/?ref=norwegianspark", fallback: "https://authy.com" },
  "duo-security": { url: "https://duo.com/pricing/?ref=norwegianspark", fallback: "https://duo.com" },
  "duo-free": { url: "https://duo.com/editions-and-pricing/duo-free/?ref=norwegianspark", fallback: "https://duo.com" },
  "duo-essentials": { url: "https://duo.com/editions-and-pricing/duo-essentials/?ref=norwegianspark", fallback: "https://duo.com" },
  "duo-advantage": { url: "https://duo.com/editions-and-pricing/duo-advantage/?ref=norwegianspark", fallback: "https://duo.com" },
  "duo-premier": { url: "https://duo.com/editions-and-pricing/duo-premier/?ref=norwegianspark", fallback: "https://duo.com" },
  "microsoft-authenticator": { url: "https://microsoft.com/security/mobile-authenticator-app/?ref=norwegianspark", fallback: "https://microsoft.com" },
  "microsoft-authenticator-business": { url: "https://microsoft.com/security/business/identity-access/azure-active-directory-mfa/?ref=norwegianspark", fallback: "https://microsoft.com" },
  "google-authenticator": { url: "https://googleauthenticator.net/?ref=norwegianspark", fallback: "https://googleauthenticator.net" },
  "google-authenticator-android": { url: "https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&ref=norwegianspark", fallback: "https://play.google.com" },
  "google-authenticator-ios": { url: "https://apps.apple.com/app/google-authenticator/id388497605/?ref=norwegianspark", fallback: "https://apps.apple.com" },
  "yubico-authenticator": { url: "https://yubico.com/products/yubico-authenticator/?ref=norwegianspark", fallback: "https://yubico.com" },
  "yubikey-5-nfc": { url: "https://yubico.com/product/yubikey-5-nfc/?ref=norwegianspark", fallback: "https://yubico.com" },
  "yubikey-5c": { url: "https://yubico.com/product/yubikey-5c/?ref=norwegianspark", fallback: "https://yubico.com" },
  "yubikey-5ci": { url: "https://yubico.com/product/yubikey-5ci/?ref=norwegianspark", fallback: "https://yubico.com" },
  "yubikey-5c-nfc": { url: "https://yubico.com/product/yubikey-5c-nfc/?ref=norwegianspark", fallback: "https://yubico.com" },
  "yubikey-bio": { url: "https://yubico.com/product/yubikey-bio/?ref=norwegianspark", fallback: "https://yubico.com" },
  "yubikey-security-key": { url: "https://yubico.com/product/security-key-nfc/?ref=norwegianspark", fallback: "https://yubico.com" },
  "aegis-authenticator": { url: "https://getaegis.app/?ref=norwegianspark", fallback: "https://getaegis.app" },
  "aegis-android": { url: "https://play.google.com/store/apps/details?id=com.beemdevelopment.aegis&ref=norwegianspark", fallback: "https://getaegis.app" },
  "raivo-otp": { url: "https://raivo-otp.com/?ref=norwegianspark", fallback: "https://raivo-otp.com" },
  "raivo-ios": { url: "https://apps.apple.com/app/raivo-otp/id1459042137/?ref=norwegianspark", fallback: "https://raivo-otp.com" },
  "lastpass-authenticator": { url: "https://lastpass.com/auth/?ref=norwegianspark", fallback: "https://lastpass.com" },
  "lastpass-authenticator-premium": { url: "https://lastpass.com/auth/?ref=norwegianspark&plan=premium", fallback: "https://lastpass.com" },
  "authy-business": { url: "https://authy.com/business/?ref=norwegianspark", fallback: "https://authy.com" },
  "duo-business": { url: "https://duo.com/editions-and-pricing/duo-business/?ref=norwegianspark", fallback: "https://duo.com" },
  "yubico-enterprise": { url: "https://yubico.com/products/yubikey-as-a-service/?ref=norwegianspark", fallback: "https://yubico.com" },
  "yubikey-5-nano": { url: "https://yubico.com/product/yubikey-5-nano/?ref=norwegianspark", fallback: "https://yubico.com" },
  "yubikey-5c-nano": { url: "https://yubico.com/product/yubikey-5c-nano/?ref=norwegianspark", fallback: "https://yubico.com" },
  "authy-ios": { url: "https://apps.apple.com/app/authy/id494168017/?ref=norwegianspark", fallback: "https://authy.com" },
  "authy-android": { url: "https://play.google.com/store/apps/details?id=com.authy.authy&ref=norwegianspark", fallback: "https://authy.com" },
  "duo-mobile-ios": { url: "https://apps.apple.com/app/duo-mobile/id422663827/?ref=norwegianspark", fallback: "https://duo.com" },
  "duo-mobile-android": { url: "https://play.google.com/store/apps/details?id=com.duosecurity.duomobile&ref=norwegianspark", fallback: "https://duo.com" },
  "microsoft-authenticator-ios": { url: "https://apps.apple.com/app/microsoft-authenticator/id983156458/?ref=norwegianspark", fallback: "https://microsoft.com" },
  "microsoft-authenticator-android": { url: "https://play.google.com/store/apps/details?id=com.azure.authenticator&ref=norwegianspark", fallback: "https://microsoft.com" },
  "yubico-2pack": { url: "https://yubico.com/product/yubikey-5-nfc-two-pack/?ref=norwegianspark", fallback: "https://yubico.com" },
  "yubikey-enterprise-pack": { url: "https://yubico.com/products/yubikey-5-enterprise/?ref=norwegianspark", fallback: "https://yubico.com" },
  "aegis-github": { url: "https://github.com/beemdevelopment/Aegis/?ref=norwegianspark", fallback: "https://getaegis.app" },
  "raivo-macos": { url: "https://raivo-otp.com/download/macos/?ref=norwegianspark", fallback: "https://raivo-otp.com" },
  "lastpass-authenticator-ios": { url: "https://apps.apple.com/app/lastpass-authenticator/id1079110004/?ref=norwegianspark", fallback: "https://lastpass.com" },
  "lastpass-authenticator-android": { url: "https://play.google.com/store/apps/details?id=com.lastpass.authenticator&ref=norwegianspark", fallback: "https://lastpass.com" },
  "duo-hardware-tokens": { url: "https://duo.com/product/trusted-users/two-factor-authentication/hardware-tokens/?ref=norwegianspark", fallback: "https://duo.com" },

  // ═══════════════════════════════════════
  // EASEUS — PC migration & backup
  // ═══════════════════════════════════════
  "easeus": { url: "https://www.anrdoezrs.net/click-101728212-15398435", fallback: "https://easeus.com" },
  "easeus-backup": { url: "https://www.jdoqocy.com/click-101728212-15398448", fallback: "https://easeus.com" },
}

export function getAffiliateUrl(slug: string) {
  return AFFILIATE_MAP[slug]?.url
}

export function getFallbackUrl(slug: string) {
  return AFFILIATE_MAP[slug]?.fallback
}

export function getAllSlugs() {
  return Object.keys(AFFILIATE_MAP)
}
